# Generated by Django 5.0.1 on 2024-01-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recor',
            new_name='Record',
        ),
    ]
